#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

ROOT="$(cd "$(dirname "$0")"; pwd)"


ln -sf "$ROOT/vimrc" ~/.vimrc
ln -sf "$ROOT/gvimrc" ~/.gvimrc
ln -sf "$ROOT/ideavimrc" ~/.ideavimrc
ln -sF "$ROOT/nvim" ~/.config/nvim
