call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-abolish'
Plug 'pangloss/vim-javascript'
Plug 'altercation/vim-colors-solarized'
Plug 'tpope/vim-fugitive'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'kana/vim-textobj-user'
Plug 'tpope/vim-unimpaired'
Plug 'vim-ruby/vim-ruby'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'mgamba/j-split'
Plug 'jgdavey/vim-blockle'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-rake'
Plug 'ddrscott/vim-side-search'
Plug 'mbbill/undotree'
Plug 'jremmen/vim-ripgrep'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-bundler'
Plug 'dense-analysis/ale'
Plug 'MaxMEllon/vim-jsx-pretty'
Plug 'vim-scripts/regreplop.vim'
Plug 'tomasr/molokai'
Plug 'tpope/vim-dispatch'
Plug 'janko/vim-test'
Plug 'SirVer/ultisnips'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'elzr/vim-json'
Plug 'sjl/vitality.vim'
Plug 'mvolkmann/vim-js-arrow-function'
Plug 'chrisbra/csv.vim'
Plug 'derekwyatt/vim-scala'
Plug 'tpope/vim-rbenv'
Plug 'Raimondi/delimitMate'
Plug 'tinted-theming/base16-vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'georgewitteman/vim-fish'
call plug#end()

source ~/.vim/config/init.vim
source ~/.vim/config/settings.vim
source ~/.vim/config/filetypes.vim
source ~/.vim/config/mappings.vim
source ~/.vim/config/plugins.vim

runtime config/init/**.vim

